defaults:
  - _self_
  - dataset: cifar_no_val
  - network: resnet18-cifar-simclr-pretrained
  - training_strategy: final_cifar_transfer
  - query_strategy: margin
  - initial_selection_strategy: kmeans_init_class_anchor_cifar
  - scenario: cifar_hb

seed: 0
epochs: 150
batch_size: 128
num_workers: 0

evaluate_train: False
evaluate_unl: False
evaluate_val: False
save_train_embeddings: False
save_unl_embeddings: False
save_val_embeddings: False
validate_on_test: False

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  weight_decay: 1e-4

lr_scheduler:
  _target_: utilities.instantiate_utils.create_sequential_lr
  _partial_: True
  lr_schedulers:
    - _target_: torch.optim.lr_scheduler.LinearLR  # Linear Warmup
      _partial_: True
      start_factor: 1e-3
      end_factor: 1
      total_iters: 10
    - _target_: torch.optim.lr_scheduler.CosineAnnealingLR # Decline rest of the epochs in an cosine fashion ...
      _partial_: True
      eta_min: 5e-5
      T_max: 140
  milestones: [10]

hydra:
  mode: MULTIRUN
  job:
    chdir: True
  sweep:
    dir: results/cifar_transfer_mask/
    subdir: seed_${seed}/${hydra.runtime.choices.query_strategy}/${hydra.runtime.choices.training_strategy}/

