defaults:
  - _self_
  - dataset: imagewoof
  - network: resnet18-imagewoof-simclr-pretrained
  - training_strategy: final_woof_dual_dense
  - query_strategy: margin
  - initial_selection_strategy: kmeans_init_class_anchor_imagewoof
  - scenario: imagewoof_hb

seed: 0
epochs: 300
batch_size: 64
num_workers: 4

evaluate_train: False
evaluate_unl: False
evaluate_val: False
save_train_embeddings: False
save_unl_embeddings: False
save_val_embeddings: False
validate_on_test: False

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  weight_decay: 1e-4

lr_scheduler:
  _target_: utilities.instantiate_utils.create_sequential_lr
  _partial_: True
  lr_schedulers:
    - _target_: torch.optim.lr_scheduler.LinearLR  # Linear Warmup
      _partial_: True
      start_factor: 1e-3
      end_factor: 1
      total_iters: 20
    - _target_: torch.optim.lr_scheduler.CosineAnnealingLR # Decline rest of the epochs in an cosine fashion ...
      _partial_: True
      eta_min: 5e-5
      T_max: 280
  milestones: [20]

hydra:
  mode: MULTIRUN
  job:
    chdir: True
  sweep:
    dir: results/woof_hb/
    subdir: seed_${seed}/${hydra.runtime.choices.network}/${hydra.runtime.choices.query_strategy}/${hydra.runtime.choices.training_strategy}/
  sweeper:
    params:
      training_strategy: final_woof_dual_dense, final_woof_dual_lth, final_woof_rand_start, final_woof_dual_rand
      query_strategy: margin, badge, saal, coreset_greedy, max_herding_rbf, uherding_rbf_adaptive
